In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Accident.csv")

In [3]:
dataset

     Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0     56  Female             27.0          No            No       1.0
1     69     NaN             46.0          No           Yes       1.0
2     46    Male             46.0         Yes           Yes       0.0
3     32    Male            117.0          No           Yes       0.0
4     60  Female             40.0         Yes           Yes       0.0
..   ...     ...              ...         ...           ...       ...
195   69  Female            111.0          No           Yes       1.0
196   30  Female              NaN          No           Yes       1.0
197   58     NaN            110.0          No           Yes       1.0
198   20    Male            103.0          No           Yes       NaN
199   56     NaN             43.0          No           NaN       1.0

[200 rows x 6 columns]

In [4]:
dataset.isnull().sum()

Age                0
Gender             8
Speed_of_Impact    4
Helmet_Used        4
Seatbelt_Used      6
Survived           3
dtype: int64

In [5]:
dataset.isna().sum()

Age                0
Gender             8
Speed_of_Impact    4
Helmet_Used        4
Seatbelt_Used      6
Survived           3
dtype: int64

In [6]:
dataset["Gender"].mode()[0]

'Female'

In [7]:
dataset["Gender"].mode()[0]

'Female'

In [8]:
dataset["Speed_of_Impact"].median()

71.5

In [9]:
dataset["Speed_of_Impact"].mean()

70.54081632653062

In [10]:
from Univariate import QuanQual

In [11]:
Quan, Qual=QuanQual.QuanQual(dataset)

Quan= ['Age', 'Speed_of_Impact', 'Survived']
Qual= ['Gender', 'Helmet_Used', 'Seatbelt_Used']

In [12]:
Table= QuanQual.Univariate_Table(Quan,dataset)

C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:20: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Mean']=dataset[columnname].mean()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:21: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Median']=dataset[columnname].median()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:22: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Mode']=dataset[columnname].mode()[0]
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:23: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Q1:25%']=dataset.describe()[columnname]['25%']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:24: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Q2:50%']=dataset.describe()[columnname]['50%']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:25: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Q3:75%']=dataset.describe()[columnname]['75%']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:26: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['99%']=np.percentile(dataset[columnname],99)
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:27: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Q4:100%']=dataset.describe()[columnname]['max']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:28: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Min']=dataset[columnname].min()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:29: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Max']=dataset[columnname].max()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:30: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['IQR']=Table[columnname]['Q3:75%']-Table[columnname]['Q1:25%']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['1.5rule']=1.5* Table[columnname]['IQR']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Lesser']= Table[columnname]['Q1:25%']-Table[columnname]['1.5rule']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Greater']= Table[columnname]['Q3:75%']+Table[columnname]['1.5rule']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:34: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Skew']=dataset[columnname].skew()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:35: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Kurtosis']=dataset[columnname].kurtosis()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:20: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Mean']=dataset[columnname].mean()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:21: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Median']=dataset[columnname].median()
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:22: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Mode']=dataset[columnname].mode()[0]
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:23: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Table[columnname]['Q1:25%']=dataset.describe()[columnname]['25%']
C:\Hope AI\AI Course\007. Data Science\001.  Univariate\003. Data Prepocessing\Univariate.py:24: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value


In [13]:
Table

            Age Speed_of_Impact  Survived
Mean     43.425       70.540816  0.502538
Median     43.5            71.5       1.0
Mode         56            77.0       1.0
Q1:25%     31.0            43.0       0.0
Q2:50%     43.5            71.5       1.0
Q3:75%     56.0            95.5       1.0
99%        69.0             NaN       NaN
Q4:100%    69.0           119.0       1.0
Min          18            20.0       0.0
Max          69           119.0       1.0
IQR        25.0            52.5       1.0
1.5rule    37.5           78.75       1.5
Lesser     -6.5          -35.75      -1.5
Greater    93.5          174.25       2.5

In [14]:
gender_mode=dataset["Gender"].mode()[0]

In [15]:
gender_mode

'Female'

In [16]:
dataset["Gender"].fillna(gender_mode, inplace= True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10940\1249025665.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Gender"].fillna(gender_mode, inplace= True)

In [17]:
dataset.isnull().sum()

Age                0
Gender             0
Speed_of_Impact    4
Helmet_Used        4
Seatbelt_Used      6
Survived           3
dtype: int64

In [18]:
dataset

     Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0     56  Female             27.0          No            No       1.0
1     69  Female             46.0          No           Yes       1.0
2     46    Male             46.0         Yes           Yes       0.0
3     32    Male            117.0          No           Yes       0.0
4     60  Female             40.0         Yes           Yes       0.0
..   ...     ...              ...         ...           ...       ...
195   69  Female            111.0          No           Yes       1.0
196   30  Female              NaN          No           Yes       1.0
197   58  Female            110.0          No           Yes       1.0
198   20    Male            103.0          No           Yes       NaN
199   56  Female             43.0          No           NaN       1.0

[200 rows x 6 columns]

In [19]:
helmet_mode=dataset["Helmet_Used"].mode()[0]

In [20]:
helmet_mode

'Yes'

In [22]:
dataset.isnull().sum()

Age                0
Gender             0
Speed_of_Impact    4
Helmet_Used        4
Seatbelt_Used      6
Survived           3
dtype: int64

In [30]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp.fit(dataset[Qual])
ds=imp.transform(dataset[Qual])
dt=pd.DataFrame(ds, columns= Qual)

In [32]:
dt

     Gender Helmet_Used Seatbelt_Used
0    Female          No            No
1    Female          No           Yes
2      Male         Yes           Yes
3      Male          No           Yes
4    Female         Yes           Yes
..      ...         ...           ...
195  Female          No           Yes
196  Female          No           Yes
197  Female          No           Yes
198    Male          No           Yes
199  Female          No           Yes

[200 rows x 3 columns]

In [33]:
dataset.columns

Index(['Age', 'Gender', 'Speed_of_Impact', 'Helmet_Used', 'Seatbelt_Used',
       'Survived'],
      dtype='object')

In [35]:
Quan

['Age', 'Speed_of_Impact', 'Survived']

In [37]:
Qual

['Gender', 'Helmet_Used', 'Seatbelt_Used']

In [36]:
dataset.isnull().sum()

Age                0
Gender             0
Speed_of_Impact    4
Helmet_Used        4
Seatbelt_Used      6
Survived           3
dtype: int64

In [38]:
cate=pd.DataFrame(dataset[Quan])

In [52]:
two=[dt, cate]

In [53]:
dataset=pd.concat(two, axis=1)

In [54]:
final

     Gender Helmet_Used Seatbelt_Used  Age  Speed_of_Impact  Survived
0    Female          No            No   56             27.0       1.0
1    Female          No           Yes   69             46.0       1.0
2      Male         Yes           Yes   46             46.0       0.0
3      Male          No           Yes   32            117.0       0.0
4    Female         Yes           Yes   60             40.0       0.0
..      ...         ...           ...  ...              ...       ...
195  Female          No           Yes   69            111.0       1.0
196  Female          No           Yes   30              NaN       1.0
197  Female          No           Yes   58            110.0       1.0
198    Male          No           Yes   20            103.0       NaN
199  Female          No           Yes   56             43.0       1.0

[200 rows x 6 columns]

In [55]:
dataset.isnull().sum()

Gender             0
Helmet_Used        0
Seatbelt_Used      0
Age                0
Speed_of_Impact    4
Survived           3
dtype: int64

In [56]:
Survived_mode=dataset["Survived"].mode()[0]

In [57]:
Survived_mode

1.0

In [58]:
dataset["Survived"].fillna(Survived_mode, inplace= True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10940\2016469640.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Survived"].fillna(Survived_mode, inplace= True)

In [60]:
dataset

     Gender Helmet_Used Seatbelt_Used  Age  Speed_of_Impact  Survived
0    Female          No            No   56             27.0       1.0
1    Female          No           Yes   69             46.0       1.0
2      Male         Yes           Yes   46             46.0       0.0
3      Male          No           Yes   32            117.0       0.0
4    Female         Yes           Yes   60             40.0       0.0
..      ...         ...           ...  ...              ...       ...
195  Female          No           Yes   69            111.0       1.0
196  Female          No           Yes   30              NaN       1.0
197  Female          No           Yes   58            110.0       1.0
198    Male          No           Yes   20            103.0       1.0
199  Female          No           Yes   56             43.0       1.0

[200 rows x 6 columns]

In [61]:
dataset.isnull().sum()

Gender             0
Helmet_Used        0
Seatbelt_Used      0
Age                0
Speed_of_Impact    4
Survived           0
dtype: int64

In [62]:
Speed_of_Impact_median=dataset["Survived"].median()

In [63]:
Speed_of_Impact_median

1.0

In [64]:
dataset['Speed_of_Impact'].fillna(Speed_of_Impact_median, inplace= True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10940\3131121458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Speed_of_Impact'].fillna(Speed_of_Impact_median, inplace= True)

In [65]:
dataset

     Gender Helmet_Used Seatbelt_Used  Age  Speed_of_Impact  Survived
0    Female          No            No   56             27.0       1.0
1    Female          No           Yes   69             46.0       1.0
2      Male         Yes           Yes   46             46.0       0.0
3      Male          No           Yes   32            117.0       0.0
4    Female         Yes           Yes   60             40.0       0.0
..      ...         ...           ...  ...              ...       ...
195  Female          No           Yes   69            111.0       1.0
196  Female          No           Yes   30              1.0       1.0
197  Female          No           Yes   58            110.0       1.0
198    Male          No           Yes   20            103.0       1.0
199  Female          No           Yes   56             43.0       1.0

[200 rows x 6 columns]

In [66]:
dataset.isna().sum()

Gender             0
Helmet_Used        0
Seatbelt_Used      0
Age                0
Speed_of_Impact    0
Survived           0
dtype: int64